### ISSUE TITLE
Insight API implementation and debugging

### ISSUE THREAD

**Issue by bborumoore** [bborumoore/mars-daily#2]
- [x] Ensure that we can reach the Insight API
- [x] Receive a valid response from a static call
- [x] Receive a valid response from a dynamic call
- [x] Parse response for wanted data
- [x] Display wanted data on screen
- [ ] Index displayed data into local storage
- [ ] Successfully recall stored data
- [x] Successfully transition from Live data to stored data
- [x] Successfully transition from stored data to live data

**Comment by ClairePhillips51** [comment]
Never set up local storage for the pictures.
