### ISSUE TITLE
LocalStorage Setup

### ISSUE THREAD

**Issue by bborumoore** [bborumoore/mars-daily#9]
- [x] Successfully store information on local drive
- [x] Successfully retrieve information from local drive
- [ ] Store static text/img pairing
- [ ] Store dynamic text/img pairing
- [ ] store an array of text/img pairings
- [ ] use locally stored text/img pairing to generate a card on the page
- [x] use carousel to go through text/img pariings on page

**Comment by ClairePhillips51** [comment]
Our local storage is tied to the modal with getting the users name so they are greeted when they log in.
